---
- name: Install NFS client packages
  ansible.builtin.apt:
    name: nfs-common
    state: present
    update_cache: yes

- name: Create mount directory
  ansible.builtin.file:
    path: /mnt/share
    state: directory

- name: Mount NFS share
  ansible.builtin.mount:
    path: /mnt/share
    src: "192.168.1.1:/share"
    fstype: nfs
    opts: defaults
    state: mounted
